CREATE TABLE VOLUNTEER_T (
    VolunteerID INT AUTO_INCREMENT PRIMARY KEY,
    VolunteerName VARCHAR(255)
);

CREATE TABLE EMPLOYEE_T (
    EmployeeID INT AUTO_INCREMENT PRIMARY KEY,
    EmployeeName VARCHAR(255),
    EmployeeContact VARCHAR(20)
);

CREATE TABLE FUNDRAISING_EVENT_T (
    EventNum INT AUTO_INCREMENT PRIMARY KEY,
    EventTime DATETIME,
    EmployeeID INT,
    VolunteerID INT,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE_T(EmployeeID),
    FOREIGN KEY (VolunteerID) REFERENCES VOLUNTEER_T(VolunteerID)
);

CREATE TABLE PAYMENT_T (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY,
    Amount DECIMAL(10,2),
    Date DATE,
    DonatorID INT,
    FOREIGN KEY (DonatorID) REFERENCES DONATOR_T(DonatorID)
);

CREATE TABLE CHARITY_T (
    OrganizationID INT AUTO_INCREMENT PRIMARY KEY,
    O_Name VARCHAR(255),
    O_Location VARCHAR(255),
    RecipientID INT,
    FOREIGN KEY (RecipientID) REFERENCES RECIPIENT_T(RecipientID)
);

CREATE TABLE RECIPIENT_T (
    RecipientID INT AUTO_INCREMENT PRIMARY KEY,
    RecipientName VARCHAR(255)
);

CREATE TABLE DONATOR_T (
    DonatorID INT AUTO_INCREMENT PRIMARY KEY,
    D_Name VARCHAR(255),
    D_Phone VARCHAR(20)
);

CREATE TABLE PROJECT_T (
    ProjectID INT AUTO_INCREMENT PRIMARY KEY,
    Project_Name VARCHAR(255),
    Project_Description TEXT,
    Submit_Date DATE,
    VolunteerID INT,
    EmployeeID INT,
    FOREIGN KEY (VolunteerID) REFERENCES VOLUNTEER_T(VolunteerID),
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE_T(EmployeeID)
);

CREATE TABLE ENQUIRY_T (
    EnquiryID INT AUTO_INCREMENT PRIMARY KEY,
    EnquiryType VARCHAR(100),
    DonatorID INT,
    FOREIGN KEY (DonatorID) REFERENCES DONATOR_T(DonatorID)
);
